-- phpMyAdmin SQL Dump
-- version 5.0.4deb2+deb11u1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 28, 2022 at 09:31 PM
-- Server version: 10.5.15-MariaDB-0+deb11u1
-- PHP Version: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Restaurant_DB`
--

-- --------------------------------------------------------

--
-- Table structure for table `Customers`
--

CREATE TABLE `Customers` (
  `ID` varchar(10) NOT NULL COMMENT 'Randomly generated',
  `Name` varchar(30) NOT NULL,
  `Salt` varchar(20) NOT NULL COMMENT 'Check against employee DB',
  `PW` varchar(50) NOT NULL,
  `Last_login_time` datetime NOT NULL,
  `Logged_in` tinyint(1) NOT NULL,
  `Status` int(11) NOT NULL COMMENT 'See status info',
  `Locked` tinyint(1) NOT NULL,
  `Mistakes` int(1) NOT NULL COMMENT 'Failed logins',
  `2FA` tinyint(1) NOT NULL,
  `2FA_ID` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `Employees`
--

CREATE TABLE `Employees` (
  `ID` varchar(10) NOT NULL COMMENT 'Randomly generated',
  `Name` varchar(30) NOT NULL,
  `Salt` varchar(20) NOT NULL COMMENT 'Check against customer DB',
  `PW` varchar(50) NOT NULL,
  `Last_login` datetime NOT NULL,
  `Logged_in` tinyint(1) NOT NULL,
  `Locked` tinyint(1) NOT NULL,
  `Mistakes` int(1) NOT NULL COMMENT 'Failed logins',
  `2FA_ID` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `Offers`
--

CREATE TABLE `Offers` (
  `ID` varchar(10) NOT NULL COMMENT 'Randomly generated',
  `Active` tinyint(1) NOT NULL,
  `Code_string` varchar(10) DEFAULT NULL,
  `Product_ID` int(4) DEFAULT NULL COMMENT 'FK-Products.ID, optional',
  `Product_tag` varchar(10) DEFAULT NULL COMMENT 'Optional,either this or Product_ID must be populated',
  `Effect` int(5) NOT NULL COMMENT 'Effect script_ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `Orders`
--

CREATE TABLE `Orders` (
  `ID` varchar(10) NOT NULL COMMENT 'Randomly generated',
  `Manifest_ID` varchar(10) NOT NULL,
  `User_ID` varchar(10) NOT NULL COMMENT 'Foreign key-Customers.User_ID',
  `Time` datetime NOT NULL,
  `Flag` int(4) DEFAULT NULL,
  `Approved` tinyint(1) NOT NULL,
  `Fufilled` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `Products`
--

CREATE TABLE `Products` (
  `ID` int(4) NOT NULL COMMENT '4 digit ID code',
  `Name` varchar(30) NOT NULL,
  `Info` varchar(45) NOT NULL COMMENT 'Path to info files',
  `Price` float(6,2) NOT NULL,
  `Stock` int(11) NOT NULL DEFAULT 0,
  `Promoted` tinyint(1) DEFAULT 0,
  `Desc_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Desc_json`)),
  `Info_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Info_json`)),
  `Add_info_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`Add_info_json`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `Products`
--

INSERT INTO `Products` (`ID`, `Name`, `Info`, `Price`, `Stock`, `Promoted`, `Desc_json`, `Info_json`, `Add_info_json`) VALUES
(1, 'Soup of the day', '\\0000-Starters\\0001-Soup_of_the_day\\C:\\httpd-', 2.50, 0, 1, '{\"Nutritional_info\":{\"Calories\":100,\"Total_fat\":0.7,\"Saturated_fat\":0,\"Sugars\":1.8,\"Salt\":1},\"Price\":2.5,\"Prep_time\":4,\"Parallel_time\":2,\"Batch_time\":12,\"Ingredients\":[\"WATER\",\"MILK\",\"WHEAT\",\"SALT\",\"FLOUR\",\"VARIOUS\"],\"Alergens\":[\"MILK\",\"WHEAT\",\"HERBS\"],\"Warnings\":[\"CONTAINS HERBS\",\"CONTAINS WHEAT\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Soup of the day\",\"Subtitle\":\"Something new every day\",\"Desc\":\"Today\\u0027s special soup\",\"P1\":\"Our special soup is made fesh every day by our chef with a new recipie to give you something unique each day\",\"P2\":\"The soup may contain a variety of different flavours and tastes from day to day.\",\"P3\":\"The soup may contain various allergens that change daily, please check the warnings before ordering\",\"Major_note\":\"The soup changes each day\",\"Minor_note\":\"Most versions of the soup are vegetarian, but not all are vegan\"}', '{\"Serving_size\":200,\"Trans_fat\":0.1,\"Polyunsaturated_fat\":0.1,\"Monounsaturated_fat\":0.1,\"Cholesterol\":1,\"Sodium\":0.3,\"Total_carbohydrates\":7.4,\"Dietary_fibre\":3,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":5,\"Calcium\":2,\"Iron\":0.25,\"Vitamin_d\":0.2,\"Potassium\":0.3,\"Vitamin_a\":0.2,\"Vitamin_c\":0.1,\"Vitamin_e\":0.2,\"Vitamin_B12\":0.1}'),
(2, 'Fish goujons', '\\0000-Starters\\0002-Fish_goujons\\C:\\httpd-2.4', 4.50, 0, 1, '{\"Nutritional_info\":{\"Calories\":237,\"Total_fat\":10.1,\"Saturated_fat\":0,\"Sugars\":0.6,\"Salt\":1.06},\"Price\":4.5,\"Prep_time\":8,\"Parallel_time\":6,\"Batch_time\":8,\"Ingredients\":[\"FISH\",\"WATER\",\"RICE FLOUR\",\"MAIZE STARCH\",\"MAIZE FLOUR\",\"RAPESEED OIL\",\"SALT\",\"DEXTROSE\",\"PEPPER\",\"E450\",\"E415\"],\"Alergens\":[\"PEPPER\"],\"Warnings\":[\"MAY CONTAIN BONE\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Fish goujons\",\"Subtitle\":\"Tasky battered fish\",\"Desc\":\"Battered cod\",\"P1\":\"Sustainably sourced cod fillets in a delicous batter with plenty of seasoning.\",\"P2\":\"Very crisp without leaving a mess of crumbs behind\",\"P3\":\"Eco-friendly and sustainable sourced from the north sea\",\"Major_note\":\"Species: cod\",\"Minor_note\":\"\"}', '{\"Serving_size\":250,\"Trans_fat\":0.4,\"Polyunsaturated_fat\":0.4,\"Monounsaturated_fat\":0.3,\"Cholesterol\":5,\"Sodium\":4,\"Total_carbohydrates\":23.5,\"Dietary_fibre\":16,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":10.9,\"Calcium\":23,\"Iron\":0.5,\"Vitamin_d\":3,\"Potassium\":0.7,\"Vitamin_a\":1,\"Vitamin_c\":2,\"Vitamin_e\":5,\"Vitamin_B12\":2}'),
(3, 'Prawn coctail', '\\0000-Starters\\0003-Prawn_cocktail\\C:\\httpd-2', 6.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":63,\"Total_fat\":0.4,\"Saturated_fat\":0,\"Sugars\":0,\"Salt\":1.75},\"Price\":6.5,\"Prep_time\":4,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"PRAWN\",\"WATER\",\"SALT\",\"LEMON\",\"PARSLEY\",\"KETCHUP\",\"MAYONNAISE\",\"WORCESTERSHIRE SAUCE\",\"PEPPER\"],\"Alergens\":[\"CRUSTACEANS\",\"PEPPER\",\"LEMON\",\"PARSLEY\",\"WORCHESTER SAUCE\",\"PEPPER\"],\"Warnings\":[\"CONATINES MANY ALERGENS\",\"SEE THAT SECTION\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Prawn coctail\",\"Subtitle\":\"A Deliciously indulgent dish\",\"Desc\":\"The classic seafood cocktail\",\"P1\":\"An indulgent coctail of prawns and a rich coctail sauce, optionaly served with lemon\",\"P2\":\"The sauce consists of a delicous seasoned combo of ketchup, mayo and worchester sauce.\",\"P3\":\"Optionaly served with parsley or a herb of your choice\",\"Major_note\":\"Conatins crustacseans\",\"Minor_note\":\"Contains several alergens, see alergens for details\"}', '{\"Serving_size\":300,\"Trans_fat\":0.05,\"Polyunsaturated_fat\":0.05,\"Monounsaturated_fat\":0.1,\"Cholesterol\":3,\"Sodium\":0.4,\"Total_carbohydrates\":0.5,\"Dietary_fibre\":0.3,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":14.3,\"Calcium\":3,\"Iron\":0.2,\"Vitamin_d\":0.1,\"Potassium\":0.2,\"Vitamin_a\":0.3,\"Vitamin_c\":0.3,\"Vitamin_e\":0.2,\"Vitamin_B12\":0.1}'),
(4, 'Breaded mushrooms', '\\0000-Starters\\0004-Breaded_mushroms\\C:\\httpd', 2.20, 0, 0, '{\"Nutritional_info\":{\"Calories\":184,\"Total_fat\":8.1,\"Saturated_fat\":0,\"Sugars\":1,\"Salt\":0.64},\"Price\":2.2,\"Prep_time\":4,\"Parallel_time\":2,\"Batch_time\":4,\"Ingredients\":[\"MUSHROOMS\",\"WHEAT\",\"FLOWER\",\"WATER\",\"SUNFLOWER OIL\",\"STARCH\",\"GLUTEN\",\"SALT\",\"PEPPER\",\"YEAST\",\"GARLIC\"],\"Alergens\":[\"WHEAT\",\"GARLIC\",\"GLUTEN\"],\"Warnings\":[\"CONTAINS GLUTEN\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Breaded mushrooms\",\"Subtitle\":\"A tasty starter\",\"Desc\":\"A famous earthy, vegan starter\",\"P1\":\"A delicous, savoury vegan starter\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":400,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":0.9,\"Cholesterol\":1,\"Sodium\":0.7,\"Total_carbohydrates\":23.8,\"Dietary_fibre\":2.3,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":2.9,\"Calcium\":0.3,\"Iron\":0.1,\"Vitamin_d\":1.3,\"Potassium\":0.2,\"Vitamin_a\":0.5,\"Vitamin_c\":0.2,\"Vitamin_e\":0.6,\"Vitamin_B12\":0.4}'),
(5, 'Cheese board', '\\0000-Starters\\0005-Small_cheese_board\\C:\\htt', 7.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":125,\"Total_fat\":50.7,\"Saturated_fat\":0,\"Sugars\":5.1,\"Salt\":2.6},\"Price\":7.5,\"Prep_time\":4,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"BRIE\",\"CHEDDAR\",\"RED LEICESTER\",\"WENSLEYDALE\",\"CRANBERRY\",\"BLUE STILTON\"],\"Alergens\":[\"MILK\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Cheese board\",\"Subtitle\":\"Classic and classy\",\"Desc\":\"A cheesboard with 6 cheeses\",\"P1\":\"A classic cheesboard offering a variety of tastes for you to enjoy.\",\"P2\":\"Contains:\\r\\nBrie\\r\\nMature cheddar\\r\\nRed leicester\\r\\nWensleydale\\r\\nCranberry\\r\\nBlue stilton\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":450,\"Trans_fat\":6,\"Polyunsaturated_fat\":6,\"Monounsaturated_fat\":7,\"Cholesterol\":7,\"Sodium\":0.8,\"Total_carbohydrates\":5.5,\"Dietary_fibre\":1,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":33.1,\"Calcium\":21,\"Iron\":0.7,\"Vitamin_d\":0.3,\"Potassium\":0.2,\"Vitamin_a\":0.4,\"Vitamin_c\":0.1,\"Vitamin_e\":0.2,\"Vitamin_B12\":0.3}'),
(6, 'Tomatoes & Mozzarella', '\\0000-Starters\\0006-Tomato_and_mozzarella\\C:\\', 3.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":203,\"Total_fat\":16,\"Saturated_fat\":0,\"Sugars\":2.6,\"Salt\":1},\"Price\":3,\"Prep_time\":3,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"MOZZARELLA\",\"TOMATOES\",\"SUNFLOWER OIL\",\"SALT\"],\"Alergens\":[\"MILK\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Tomatoes \\u0026 Mozzarella\",\"Subtitle\":\"An itallian classic\",\"Desc\":\"Classical and tasty\",\"P1\":\"Seasoned mozzarella cheese and tomatoes in sunflower oil.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":3.2,\"Polyunsaturated_fat\":3.2,\"Monounsaturated_fat\":3.7,\"Cholesterol\":3,\"Sodium\":0.8,\"Total_carbohydrates\":3.6,\"Dietary_fibre\":2.4,\"Added_sugar\":1,\"Sugar_alcohol\":0,\"Protein\":9.8,\"Calcium\":6,\"Iron\":0.3,\"Vitamin_d\":0.2,\"Potassium\":0.3,\"Vitamin_a\":0.2,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":1.5}'),
(7, 'Caesar salad', '\\0000-Starters\\0007-Caesar_salad\\C:\\httpd-2.4', 2.30, 0, 0, '{\"Nutritional_info\":{\"Calories\":137,\"Total_fat\":8.1,\"Saturated_fat\":0,\"Sugars\":2.8,\"Salt\":0.67},\"Price\":2.3,\"Prep_time\":2,\"Parallel_time\":0,\"Batch_time\":5,\"Ingredients\":[\"LETTUCE\",\"DRESSING\",\"WATER\",\"RAPESEED OIL\",\"CORNFLOWER\",\"CHEESE\",\"MILK\",\"SUGAR\",\"VINEGAR\",\"SALT\",\"EGG YOLK\",\"GARLIC\",\"ONION\",\"PEPPER\"],\"Alergens\":[\"GARLIC\",\"ONION\",\"PEPPER\"],\"Warnings\":[\"CONTAINS EGG YOLK AND UNPASTEURISED MILK\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Caesar salad\",\"Subtitle\":\"Classy, light and tasty\",\"Desc\":\"A Classy traditional salad\",\"P1\":\"Famous salad consisting of romaine lettuce with caesar dressing.\",\"P2\":\"Served with black pepper, croutons and italian cheese.\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":132,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":4.4,\"Cholesterol\":5,\"Sodium\":1.3,\"Total_carbohydrates\":10.9,\"Dietary_fibre\":1.1,\"Added_sugar\":0.5,\"Sugar_alcohol\":0,\"Protein\":4.5,\"Calcium\":3,\"Iron\":0.5,\"Vitamin_d\":5,\"Potassium\":2,\"Vitamin_a\":5,\"Vitamin_c\":6,\"Vitamin_e\":7,\"Vitamin_B12\":4}'),
(8, 'Potato salad', '\\0000-Starters\\0008-Potato_salad\\C:\\httpd-2.4', 2.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":142,\"Total_fat\":8.4,\"Saturated_fat\":0,\"Sugars\":1.9,\"Salt\":0.4},\"Price\":2,\"Prep_time\":7,\"Parallel_time\":0,\"Batch_time\":7,\"Ingredients\":[\"POTATOES\",\"MAYONNAISE\",\"VINEGAR\",\"SALT\",\"EGG\",\"MUSTARD\",\"STARCH\",\"SOUR CREAM\",\"ONIONS\"],\"Alergens\":[\"EGGS\",\"MILK\",\"MUSTARD\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Potato salad\",\"Subtitle\":\"A refreshing starter\",\"Desc\":\"A well seasoned potatoe salad\",\"P1\":\"A tasty salad made of potatoes and mayonnaise\",\"P2\":\"Topped with vinegar, salt, mustard, sour cream and onions.\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":275,\"Trans_fat\":2.3,\"Polyunsaturated_fat\":2.3,\"Monounsaturated_fat\":3,\"Cholesterol\":4.8,\"Sodium\":5,\"Total_carbohydrates\":14,\"Dietary_fibre\":1.2,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":2.2,\"Calcium\":15,\"Iron\":0.2,\"Vitamin_d\":4,\"Potassium\":2.4,\"Vitamin_a\":0.8,\"Vitamin_c\":1.1,\"Vitamin_e\":0.7,\"Vitamin_B12\":1.5}'),
(9, 'Chicken skewers', '\\0000-Starters\\0009-Chicken_skewers\\C:\\httpd-', 2.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":46,\"Total_fat\":2.8,\"Saturated_fat\":0,\"Sugars\":0.6,\"Salt\":0.24},\"Price\":2.5,\"Prep_time\":8,\"Parallel_time\":4,\"Batch_time\":8,\"Ingredients\":[\"CHICKEN\",\"WHEAT\",\"FLOWER\",\"VEGETABLE OIL\",\"SUGAR\",\"MUSTARD\",\"FLOUR\",\"SALT\",\"GARLIC POWDER\",\"PEPPER\"],\"Alergens\":[\"MUSTARD\",\"WHEAT\",\"SOYA\",\"GARLIC\"],\"Warnings\":[\"PRODUCT IS SERVED ON AN INEDIBLE WOODEN STICK\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Chicken skewers\",\"Subtitle\":\"Seasoned, ready to eat chicken\",\"Desc\":\"Satay style chicken skewers\",\"P1\":\"Succulent seasoned chicken on a stick\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"Warning: product is served on a wooden stick\",\"Minor_note\":\"\"}', '{\"Serving_size\":40,\"Trans_fat\":0.5,\"Polyunsaturated_fat\":0.5,\"Monounsaturated_fat\":0.7,\"Cholesterol\":0.8,\"Sodium\":0.7,\"Total_carbohydrates\":1.4,\"Dietary_fibre\":0.2,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":3.4,\"Calcium\":0.1,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(10, 'Vegetable fritters', '\\0000-Starters\\0010-Veg_fritters\\C:\\httpd-2.4', 2.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":193,\"Total_fat\":8.4,\"Saturated_fat\":0,\"Sugars\":2.7,\"Salt\":0.84},\"Price\":2.99,\"Prep_time\":6,\"Parallel_time\":4,\"Batch_time\":6,\"Ingredients\":[\"COURGETTES\",\"POTATO\",\"ONION\",\"PEAS\",\"CARROT\",\"WHEAT\",\"FLOUR\",\"STARCH\",\"CORRIANDER\",\"GINGER\",\"SALT\",\"PALM OIL\",\"CUMIN\",\"TUMERIC\"],\"Alergens\":[\"WHEAT\",\"CUMIN\",\"TUMERIC\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Vegetable fritters\",\"Subtitle\":\"Delicious veg starters\",\"Desc\":\"A well seasoned vegan snack\",\"P1\":\"Several delicously seasoned vegetable fritters made of potato, courgettes, onion and peas.\",\"P2\":\"Battered and seasoned with corriander, ginger, salt, palm oil, cumin and tumeric.\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":210,\"Trans_fat\":3.2,\"Polyunsaturated_fat\":3.2,\"Monounsaturated_fat\":0.9,\"Cholesterol\":7,\"Sodium\":3,\"Total_carbohydrates\":24,\"Dietary_fibre\":2.2,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":4.5,\"Calcium\":1.2,\"Iron\":0.5,\"Vitamin_d\":1,\"Potassium\":3,\"Vitamin_a\":0.8,\"Vitamin_c\":2,\"Vitamin_e\":0.3,\"Vitamin_B12\":1}'),
(11, 'Chicken fritters', '\\0000-Starters\\0011-Chicken_fritters\\C:\\httpd', 2.10, 0, 0, '{\"Nutritional_info\":{\"Calories\":257,\"Total_fat\":30,\"Saturated_fat\":0,\"Sugars\":0.5,\"Salt\":0.59},\"Price\":2.1,\"Prep_time\":5,\"Parallel_time\":4,\"Batch_time\":5,\"Ingredients\":[\"CHICKEN BREAST\",\"WHEAT\",\"FLOUR\",\"VEGETABLE OIL\",\"WATER\",\"YEAST\",\"VINEGAR\",\"GLUTEN\",\"SALT\",\"SUGAR\"],\"Alergens\":[\"GLUTEN\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:STARTER\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Chicken fritters\",\"Subtitle\":\"Crunchy and tasty\",\"Desc\":\"Breaded chicken fritters\",\"P1\":\"A delicious appetiser that\\u0027l give you a nice snack before your meal\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":270,\"Trans_fat\":3.2,\"Polyunsaturated_fat\":3.2,\"Monounsaturated_fat\":4.5,\"Cholesterol\":5,\"Sodium\":0.8,\"Total_carbohydrates\":28,\"Dietary_fibre\":2.6,\"Added_sugar\":1,\"Sugar_alcohol\":0,\"Protein\":36,\"Calcium\":1.2,\"Iron\":0.9,\"Vitamin_d\":1,\"Potassium\":0.5,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(1000, 'Sheppard\'s pie', '\\1000-Mains\\1000-Sheppard\'s_pie\\C:\\httpd-2.4.', 6.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":432,\"Total_fat\":15.9,\"Saturated_fat\":0,\"Sugars\":4.7,\"Salt\":2.28},\"Price\":6.5,\"Prep_time\":43,\"Parallel_time\":30,\"Batch_time\":90,\"Ingredients\":[\"POTATO\",\"LAMB\",\"ONION\",\"CARROT\",\"SWEDE\",\"WATER\",\"BUTTER\",\"MILK\",\"CORNFLOUR\",\"SALT\",\"TOMATO PUREE\",\"WHEAT\",\"FLOUR\",\"PEAS\"],\"Alergens\":[\"MILK\",\"WHEAT\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Sheppard\\u0027s pie\",\"Subtitle\":\"A classic british dinner\",\"Desc\":\"Sheppards pie with peas\",\"P1\":\"A heartwarming meal to fill you up after an honnest days work, a good old lamb sheppards pie.\",\"P2\":\"The pie\\u0027s other fillings are onion, carrot, swede, butter and tomato puree.\",\"P3\":\"Seasoned with salt and pepper and served with a side of peas.\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":450,\"Trans_fat\":2.1,\"Polyunsaturated_fat\":2.1,\"Monounsaturated_fat\":4.2,\"Cholesterol\":13,\"Sodium\":2,\"Total_carbohydrates\":46,\"Dietary_fibre\":6,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":23.2,\"Calcium\":5,\"Iron\":0.6,\"Vitamin_d\":0.6,\"Potassium\":2,\"Vitamin_a\":3.4,\"Vitamin_c\":1.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.8}'),
(1001, 'Chicken tikka masala', '\\1000-Mains\\1001-Chicken_tikka_masala\\C:\\http', 5.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":510,\"Total_fat\":22,\"Saturated_fat\":0,\"Sugars\":12.8,\"Salt\":1.57},\"Price\":5.5,\"Prep_time\":27,\"Parallel_time\":16,\"Batch_time\":0,\"Ingredients\":[\"PILAU RICE\",\"WATER\",\"ONION\",\"MILK\",\"MINT\",\"LEMON\",\"TUMERIC\",\"CARDAMOM\",\"MACE\",\"SAFRON\",\"MARINATED CHICKEN\",\"LOW FAT YOGURT\",\"CORIANDER\",\"GINGER\",\"GARLIC\",\"PAPRIKA\",\"PEPPER\",\"CHILLI POWDER\",\"SUGAR\",\"BUTTER\"],\"Alergens\":[\"MINT\",\"MILK\",\"NUTS\",\"GINGER\",\"GARLIC\"],\"Warnings\":[\"MAY CONTAIN TRACES OF NUTS\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Chicken tikka masala\",\"Subtitle\":\"A spicy and absorbing classic\",\"Desc\":\"Grilled and marinated chicken breast in masala sauce atop pilau rice\",\"P1\":\"Deliciously spicy and rich grilled chicken that has marinaded in masala sauce for at least 24 hours.\",\"P2\":\"The chicken is served on a bed of nutritious and fluffy pilau rice and is covered in rich, spicy masala sauce.\",\"P3\":\"\",\"Major_note\":\"Lots of allergens, see alergens section\",\"Minor_note\":\"Very spicy\"}', '{\"Serving_size\":400,\"Trans_fat\":1.4,\"Polyunsaturated_fat\":1.4,\"Monounsaturated_fat\":8.6,\"Cholesterol\":6,\"Sodium\":3,\"Total_carbohydrates\":46.6,\"Dietary_fibre\":4.8,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":29.1,\"Calcium\":18,\"Iron\":5,\"Vitamin_d\":2,\"Potassium\":8,\"Vitamin_a\":0.6,\"Vitamin_c\":1,\"Vitamin_e\":3,\"Vitamin_B12\":0.9}'),
(1002, 'Pizza with pepper and chicken', '\\1000-Mains\\1002-Pizza\\C:\\httpd-2.4.53-win64-', 5.25, 0, 0, '{\"Nutritional_info\":{\"Calories\":496,\"Total_fat\":31.4,\"Saturated_fat\":0,\"Sugars\":15,\"Salt\":2.7},\"Price\":5.25,\"Prep_time\":17,\"Parallel_time\":10,\"Batch_time\":0,\"Ingredients\":[\"WHEAT\",\"FLOUR\",\"MOZZARELLA CHEESE\",\"WATER\",\"CAJUN CHICKEN\",\"PAPRIKA\",\"GARLIC\",\"ONION POWDER\",\"HERBS\",\"TOMATO PUREE\",\"TOMATO\",\"RED PEPPERS\",\"RED ONION\"],\"Alergens\":[\"HERBS\",\"MILK\",\"PAPRIKA\"],\"Warnings\":[\"CONTAINS GLUTEN\",\"MILK AND SOYA\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Pizza with pepper and chicken\",\"Subtitle\":\"Spicy, delicious and easy to eat\",\"Desc\":\"Chicken and pepper pizza\",\"P1\":\"A deliciously tasty pizza made with the best ingredients, topped with mozzaela cheese.\",\"P2\":\"The pizza is toped with red pepper and cajun chicken\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":465,\"Trans_fat\":2.3,\"Polyunsaturated_fat\":2.3,\"Monounsaturated_fat\":3.6,\"Cholesterol\":7.8,\"Sodium\":2,\"Total_carbohydrates\":121.4,\"Dietary_fibre\":5.4,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":24.2,\"Calcium\":14,\"Iron\":0.7,\"Vitamin_d\":0.8,\"Potassium\":0.5,\"Vitamin_a\":0.5,\"Vitamin_c\":3,\"Vitamin_e\":0.6,\"Vitamin_B12\":0.8}'),
(1003, 'Burger and fries', '\\1000-Mains\\1003-Burger_and_fries\\C:\\httpd-2.', 6.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":1067,\"Total_fat\":49,\"Saturated_fat\":0,\"Sugars\":1.6,\"Salt\":1.92},\"Price\":6,\"Prep_time\":16,\"Parallel_time\":14,\"Batch_time\":0,\"Ingredients\":[\"BEEF\",\"PEA FLAKES\",\"WATER\",\"PEPPER\",\"SALT\",\"RAPESEED OIL\",\"POTATO\",\"SUNFLOWE OIL\",\"RICE FLOUR\",\"GARLIC POWDER\",\"ONION\",\"CHILLI POWDER\",\"CHEESE\"],\"Alergens\":[\"GARLIC\",\"ONION\",\"CHILLI\"],\"Warnings\":[\"CONTAINS CHILLI POWDER\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Burger and fries\",\"Subtitle\":\"Premium burger and crunchy fries\",\"Desc\":\"A scotch beef burger with cheese and fries\",\"P1\":\"A premium scotch beef burger on a tasty seaseme seed bun\",\"P2\":\"Served with a side of crunchy on the outside, fluffy on the inside seasoned chips.\",\"P3\":\"The burger can optionaly be topped with cheese, onion, tomato and lettuce.\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":441,\"Trans_fat\":7,\"Polyunsaturated_fat\":7,\"Monounsaturated_fat\":6,\"Cholesterol\":23,\"Sodium\":3,\"Total_carbohydrates\":74,\"Dietary_fibre\":10.4,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":34,\"Calcium\":12,\"Iron\":2,\"Vitamin_d\":3,\"Potassium\":0.3,\"Vitamin_a\":0.1,\"Vitamin_c\":0.7,\"Vitamin_e\":0.4,\"Vitamin_B12\":2}'),
(1004, 'Full english breakfast', '\\1000-Mains\\1004-Full_english_breakfast\\C:\\ht', 8.70, 0, 0, '{\"Nutritional_info\":{\"Calories\":895,\"Total_fat\":65.84,\"Saturated_fat\":0,\"Sugars\":14.55,\"Salt\":5},\"Price\":8.7,\"Prep_time\":25,\"Parallel_time\":9,\"Batch_time\":0,\"Ingredients\":[\"SAUSAGE\",\"BEANS\",\"BACON\",\"EGGS\",\"TOMATO\",\"MUSHROOMS\",\"HASH BROWNS\",\"BREAD\",\"SALT\",\"PEPPER\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Full english breakfast\",\"Subtitle\":\"A filling english classic\",\"Desc\":\"A classic full english breakfast\",\"P1\":\"A traditional salt of the earth meal for people who work hard and need a hearty breakfast to get them through.\",\"P2\":\"Comes with your choice of scrabled or fried eggs and your choice of seasoning\",\"P3\":\"\",\"Major_note\":\"Eggs may be fried or scrambled\",\"Minor_note\":\"\"}', '{\"Serving_size\":536,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":28.5,\"Cholesterol\":13,\"Sodium\":0.25,\"Total_carbohydrates\":33.86,\"Dietary_fibre\":6.44,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":44.7,\"Calcium\":0.9,\"Iron\":0.5,\"Vitamin_d\":0.3,\"Potassium\":3,\"Vitamin_a\":0.5,\"Vitamin_c\":0.15,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(1005, 'Paella', '\\1000-Mains\\1005-Paella\\C:\\httpd-2.4.53-win64', 5.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":460,\"Total_fat\":11.1,\"Saturated_fat\":0,\"Sugars\":5.8,\"Salt\":1.38},\"Price\":5.5,\"Prep_time\":26,\"Parallel_time\":13,\"Batch_time\":0,\"Ingredients\":[\"RISOTTO RICE\",\"TOMATO\",\"MARINATED CHICKEN\",\"PRAWN\",\"PEAS\",\"TOMATO PUREE\",\"CHORIZO\",\"PAPRIKA\",\"TUMERIC\",\"PEPPER\",\"CHILLI POWDER\",\"WHITE WINE\",\"PEPPER\"],\"Alergens\":[\"PRAWNS\",\"PAPRIKA\",\"CHORIZO\",\"TUMERIC\",\"CHILLI POWDER\",\"PEPPER\"],\"Warnings\":[\"CONTAINS PRAWNS\",\"WINE\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Paella\",\"Subtitle\":\"A delicious taste of spain\",\"Desc\":\"Chicken and prawn paella\",\"P1\":\"Classic rice and pea paella with chorizo and roasted peppers in tomato sauce.\",\"P2\":\"Comes with prawns and marinated chicken for extra flavour and taste.\",\"P3\":\"\",\"Major_note\":\"Wine optional but default\",\"Minor_note\":\"Prawns optional but default\"}', '{\"Serving_size\":350,\"Trans_fat\":0.5,\"Polyunsaturated_fat\":0.5,\"Monounsaturated_fat\":3,\"Cholesterol\":1.9,\"Sodium\":0.2,\"Total_carbohydrates\":63.2,\"Dietary_fibre\":6,\"Added_sugar\":0,\"Sugar_alcohol\":0.8,\"Protein\":23.9,\"Calcium\":3,\"Iron\":0.5,\"Vitamin_d\":0.2,\"Potassium\":0.6,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.6,\"Vitamin_B12\":2.7}'),
(1006, 'Risotto', '\\1000-Mains\\1006-Risotto\\C:\\httpd-2.4.53-win6', 3.20, 0, 0, '{\"Nutritional_info\":{\"Calories\":407,\"Total_fat\":8.5,\"Saturated_fat\":0,\"Sugars\":3.1,\"Salt\":1.5},\"Price\":3.2,\"Prep_time\":22,\"Parallel_time\":14,\"Batch_time\":0,\"Ingredients\":[\"RISOTTO RICE\",\"WATER\",\"CHICKEN BREAST PIECES\",\"MUSHROOMS\",\"MILK\",\"HALF CREAM\",\"CHEESE\",\"GARLIC\",\"PARSLEY\"],\"Alergens\":[\"PARSLEY\",\"GARLIC\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Risotto\",\"Subtitle\":\"A wholesome filler\",\"Desc\":\"Chicken and mushroom risotto\",\"P1\":\"Risotto with chicken breast in a creamy mushroom sauce.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":400,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":1.2,\"Cholesterol\":0.1,\"Sodium\":0.5,\"Total_carbohydrates\":62,\"Dietary_fibre\":1.93,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":19,\"Calcium\":3,\"Iron\":0.2,\"Vitamin_d\":0.7,\"Potassium\":2,\"Vitamin_a\":0.3,\"Vitamin_c\":0.4,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.2}'),
(1007, 'Spaghetti bolognese', '\\1000-Mains\\1007-spaghetti_bolognese\\C:\\httpd', 5.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":331,\"Total_fat\":2.4,\"Saturated_fat\":0,\"Sugars\":9.9,\"Salt\":1.45},\"Price\":5.5,\"Prep_time\":23,\"Parallel_time\":8,\"Batch_time\":0,\"Ingredients\":[\"SPAGHETTI\",\"SOYA\",\"FLOUR\",\"BARLEY\",\"TOMATO\",\"MUSHROOM\",\"WATER\",\"TOMATO\",\"ONION\",\"CARROT\",\"CELERY\",\"TOMATO PASTE\",\"GARLIC\",\"SUGAR\",\"SALT\",\"ROSEMARY\",\"PEPPER\"],\"Alergens\":[\"GARLIC\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Spaghetti bolognese\",\"Subtitle\":\"A vegan take on the classic meal\",\"Desc\":\"Vegan spaghtti bolognese\",\"P1\":\"Baked spaghetti in bolognese sauce with soya based meatless mince\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"Vegan friendly\",\"Minor_note\":\"\"}', '{\"Serving_size\":400,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":0.5,\"Cholesterol\":6,\"Sodium\":0.5,\"Total_carbohydrates\":57.1,\"Dietary_fibre\":6.1,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":17.1,\"Calcium\":2.3,\"Iron\":0.5,\"Vitamin_d\":0.5,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.3,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.9}'),
(1008, 'Meatballs and pasta', '\\1000-Mains\\1008-Meatballs_and_pasta\\C:\\httpd', 4.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":836,\"Total_fat\":18.6,\"Saturated_fat\":0,\"Sugars\":11,\"Salt\":2.4},\"Price\":4.99,\"Prep_time\":16,\"Parallel_time\":10,\"Batch_time\":0,\"Ingredients\":[\"PENNE PASTA\",\"PORK\",\"BEEF\",\"WHEAT\",\"ONIONS\",\"PARSLEY\",\"GARLIC\",\"OREGANO\",\"SALT\",\"PEPPER\",\"WATER\",\"TOMATES\",\"CHEESE\",\"CORNFLOWER\"],\"Alergens\":[\"PARSLEY\",\"GARLIC\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Meatballs and pasta\",\"Subtitle\":\"Rich and filling\",\"Desc\":\"Meatball and pasta bake\",\"P1\":\"Pork and beef meatballs on top of penne pasta baked in a rich tomato sauce.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"50/50 split of pork and beef meatballs\",\"Minor_note\":\"\"}', '{\"Serving_size\":700,\"Trans_fat\":2,\"Polyunsaturated_fat\":2,\"Monounsaturated_fat\":5,\"Cholesterol\":12,\"Sodium\":0.8,\"Total_carbohydrates\":104,\"Dietary_fibre\":16.6,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":44,\"Calcium\":3,\"Iron\":0.7,\"Vitamin_d\":2,\"Potassium\":0.8,\"Vitamin_a\":0.6,\"Vitamin_c\":0.3,\"Vitamin_e\":0.5,\"Vitamin_B12\":1}'),
(1009, 'Roast beef', '\\1000-Mains\\1009-Roast_beef_&_veg\\C:\\httpd-2.', 3.25, 0, 0, '{\"Nutritional_info\":{\"Calories\":532,\"Total_fat\":14.7,\"Saturated_fat\":0,\"Sugars\":0.6,\"Salt\":3.8},\"Price\":3.25,\"Prep_time\":8,\"Parallel_time\":5,\"Batch_time\":180,\"Ingredients\":[\"BEEF\",\"CARROTS\",\"BROCOLI\",\"LETTUCE\",\"TOMMATO\",\"SALT\",\"VINEGAR\",\"GARLIC\",\"PARSLEY\"],\"Alergens\":[\"GARLIC\",\"PARSLEY\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Roast beef\",\"Subtitle\":\"An old british staple\",\"Desc\":\"Roast cured beef and vegetables\",\"P1\":\"Cured rost beef with seasoned vegetables, filling, tasty and nutritious.\",\"P2\":\"Served with your choice of curing method, vegetables and seasoning\",\"P3\":\"\",\"Major_note\":\"Selectable curring method\",\"Minor_note\":\"Selectable vegetables\"}', '{\"Serving_size\":300,\"Trans_fat\":0.9,\"Polyunsaturated_fat\":0.9,\"Monounsaturated_fat\":5.3,\"Cholesterol\":17,\"Sodium\":0.6,\"Total_carbohydrates\":1.5,\"Dietary_fibre\":1.5,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":70.5,\"Calcium\":3,\"Iron\":0.75,\"Vitamin_d\":3,\"Potassium\":0.9,\"Vitamin_a\":0.3,\"Vitamin_c\":2.1,\"Vitamin_e\":1.3,\"Vitamin_B12\":0.8}'),
(1010, 'Curry', '\\1000-Mains\\1010-Curry\\C:\\httpd-2.4.53-win64-', 5.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":451,\"Total_fat\":23.8,\"Saturated_fat\":0,\"Sugars\":8.4,\"Salt\":1.71},\"Price\":5.99,\"Prep_time\":23,\"Parallel_time\":8,\"Batch_time\":0,\"Ingredients\":[\"CHICKEN BREAST\",\"ONION\",\"TOMATO\",\"COCOUNT\",\"GARLIC PUREE\",\"GINGER\",\"RAPESEED OIL\",\"SPICED\",\"MUSTARD\",\"LOW FAT YOGURT\",\"MILK\",\"SALT\",\"LEMON JUICE\",\"PEPPER\",\"SUGAR\",\"FLOUR\"],\"Alergens\":[\"COCONUT\",\"GARLIC\",\"GINGER\",\"MUSTARD\",\"MILK\"],\"Warnings\":[\"VERY SPICY\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Curry\",\"Subtitle\":\"Spicy and mouthwatering\",\"Desc\":\"Chicken curry with chutney,bread and popadoms\",\"P1\":\"Marinated chicken breast in curry sauce, spiced and with coconut sauce\",\"P2\":\"Served with mango chutney, naan bread and popadoms\",\"P3\":\"\",\"Major_note\":\"Very spicy\",\"Minor_note\":\"Contains milk\"}', '{\"Serving_size\":350,\"Trans_fat\":1.6,\"Polyunsaturated_fat\":1.6,\"Monounsaturated_fat\":2.8,\"Cholesterol\":4.2,\"Sodium\":2.3,\"Total_carbohydrates\":14,\"Dietary_fibre\":8.4,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":40.95,\"Calcium\":4,\"Iron\":1.1,\"Vitamin_d\":2.3,\"Potassium\":0.5,\"Vitamin_a\":0.3,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":1.6}'),
(1011, 'Lasagne', '\\1000-Mains\\1011-Lasagne\\C:\\httpd-2.4.53-win6', 4.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":895,\"Total_fat\":44.6,\"Saturated_fat\":0,\"Sugars\":19.8,\"Salt\":4.54},\"Price\":4.99,\"Prep_time\":28,\"Parallel_time\":16,\"Batch_time\":28,\"Ingredients\":[\"BEEF\",\"MILK\",\"EGG PASTA\",\"EGG\",\"TOMATO\",\"WATER\",\"ONION\",\"CARROT\",\"FLOUR\",\"TOMATO PUREE\",\"CELERY\",\"GARLIC\",\"CHEESE DOUBLE CREAM\",\"SALT\",\"YEAST EXTRACT\",\"SUGAR\"],\"Alergens\":[\"GARLIC\",\"CELERY\"],\"Warnings\":[\"CONTAINS EGG AND MILK\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Lasagne\",\"Subtitle\":\"Tasty, warming and filling\",\"Desc\":\"Beef Lasagne with egg bechamel sauce and cheese\",\"P1\":\"A rich lasagne filled with ground beef, Delicious tomato sauce between layers of egg pasta.\",\"P2\":\"Each layer is topped with cheese and expertly seasoned for extra flavour\",\"P3\":\"\",\"Major_note\":\"Contains egg and milk\",\"Minor_note\":\"\"}', '{\"Serving_size\":800,\"Trans_fat\":2.3,\"Polyunsaturated_fat\":2.3,\"Monounsaturated_fat\":4.7,\"Cholesterol\":6.9,\"Sodium\":1.4,\"Total_carbohydrates\":84,\"Dietary_fibre\":5.6,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":60.6,\"Calcium\":1.7,\"Iron\":0.95,\"Vitamin_d\":2,\"Potassium\":0.8,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.6,\"Vitamin_B12\":3.4}'),
(1012, 'Beef wellington', '\\1000-Mains\\1012-Beef_wellington\\C:\\httpd-2.4', 8.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":736,\"Total_fat\":48,\"Saturated_fat\":0,\"Sugars\":0,\"Salt\":2.46},\"Price\":8.5,\"Prep_time\":8,\"Parallel_time\":4,\"Batch_time\":120,\"Ingredients\":[\"BEEF FILLET\",\"OLIVE OIL\",\"MUSHROOMS\",\"BUTTER\",\"THYME\",\"WHITE WINE\",\"PROSCIUTTO\",\"FLOUR\",\"MILK\",\"EGG\",\"SUGAR\",\"SALT\",\"\"],\"Alergens\":[\"THYME\"],\"Warnings\":[\"CONTAINS WHITE WINE\",\"MILK AND EGGS\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"Beef wellington\",\"Subtitle\":\"A Distinguished meal\",\"Desc\":\"Aberdeen angus beef wellington in puff pastry\",\"P1\":\"Perfectly cooked and seasoned quality beef wrapped in A light and crispy puff pastry.\",\"P2\":\"Crispy, crumbly and seasoned to perfection, a truely high class experience.\",\"P3\":\"\",\"Major_note\":\"Contains white wine\",\"Minor_note\":\"\"}', '{\"Serving_size\":879,\"Trans_fat\":2.3,\"Polyunsaturated_fat\":2.3,\"Monounsaturated_fat\":5.6,\"Cholesterol\":3.7,\"Sodium\":2.4,\"Total_carbohydrates\":32,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":50,\"Calcium\":1,\"Iron\":1.1,\"Vitamin_d\":0.9,\"Potassium\":0.6,\"Vitamin_a\":0.3,\"Vitamin_c\":2.6,\"Vitamin_e\":0.2,\"Vitamin_B12\":1}'),
(1013, 'bbq ribs', '\\1000-Mains\\1013-BBQ_ribs\\C:\\httpd-2.4.53-win', 5.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":597,\"Total_fat\":38,\"Saturated_fat\":0,\"Sugars\":15,\"Salt\":1.1},\"Price\":5,\"Prep_time\":18,\"Parallel_time\":13,\"Batch_time\":0,\"Ingredients\":[\"PORK RIBS\",\"HONEY BBQ SAUCE\",\"TOMATO PUREE\",\"MOLASSES\",\"CORNFLOUR\",\"WATER\",\"SALT\",\"BARLEY\",\"MALT\",\"SALT\",\"PEPPER\",\"PAPRIKA\",\"SUGAR\",\"ONION\",\"VINEGAR\",\"PEPPERS\"],\"Alergens\":[\"PEPPERS\",\"PAPRIKA\"],\"Warnings\":[\"CONTAINS BONES\"],\"Tags\":[\"CATEGORY:MAINS\",\"VEGAN:FALSE\",\"VEGETARIAN:FALSE\"]}', '{\"Title\":\"bbq ribs\",\"Subtitle\":\"Delicious BBq ribs\",\"Desc\":\"BBQ ribs with sauce\",\"P1\":\"Delicious pork ribs in a sweet, spicy and sticky bbq sauce\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"Conatins bones\",\"Minor_note\":\"\"}', '{\"Serving_size\":600,\"Trans_fat\":2.8,\"Polyunsaturated_fat\":2.8,\"Monounsaturated_fat\":8.9,\"Cholesterol\":15,\"Sodium\":2,\"Total_carbohydrates\":18,\"Dietary_fibre\":3.9,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":43,\"Calcium\":3.5,\"Iron\":0.3,\"Vitamin_d\":2.3,\"Potassium\":2.5,\"Vitamin_a\":0.1,\"Vitamin_c\":0.9,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.8}'),
(2001, 'Chips', '\\2000-Sides\\2001-Chips\\C:\\httpd-2.4.53-win64-', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":149,\"Total_fat\":4.5,\"Saturated_fat\":0,\"Sugars\":0.5,\"Salt\":0.5},\"Price\":1.99,\"Prep_time\":7,\"Parallel_time\":5,\"Batch_time\":7,\"Ingredients\":[\"POTATOES\",\"SUNFLOWER OIL\",\"RICE FLOUR\",\"POTATO STARCH\",\"SALT\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chips\",\"Subtitle\":\"Crispy, crunchy, fluffy, tasty\",\"Desc\":\"Seasoned potato chips\",\"P1\":\"Crispy on the outside and fluffy on the inside and well seasoned, try our famous fries today\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":133,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":0.7,\"Cholesterol\":1.1,\"Sodium\":0.3,\"Total_carbohydrates\":23,\"Dietary_fibre\":3,\"Added_sugar\":0.1,\"Sugar_alcohol\":0,\"Protein\":2.5,\"Calcium\":0,\"Iron\":0.1,\"Vitamin_d\":1.2,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.2,\"Vitamin_B12\":0.3}'),
(2002, 'Cheesy chips', '\\2000-Sides\\2002-Cheesy_chips\\C:\\httpd-2.4.53', 2.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":250,\"Total_fat\":12.3,\"Saturated_fat\":0,\"Sugars\":0.75,\"Salt\":0.9},\"Price\":2.5,\"Prep_time\":8,\"Parallel_time\":5,\"Batch_time\":8,\"Ingredients\":[\"\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Cheesy chips\",\"Subtitle\":\"Cheesy and crunchy chips\",\"Desc\":\"Cheesy potato chips\",\"P1\":\"Our classic crunch and fluffy seasoned chips, but topped with cheese for extra taste\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":157,\"Trans_fat\":1.3,\"Polyunsaturated_fat\":1.3,\"Monounsaturated_fat\":3.8,\"Cholesterol\":1.9,\"Sodium\":0.6,\"Total_carbohydrates\":23.5,\"Dietary_fibre\":3,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":8.9,\"Calcium\":1.85,\"Iron\":0.1,\"Vitamin_d\":1.2,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.2,\"Vitamin_B12\":1.1}'),
(2003, 'Curley fries', '\\2000-Sides\\2003-Curly_fries\\C:\\httpd-2.4.53-', 2.20, 0, 0, '{\"Nutritional_info\":{\"Calories\":149,\"Total_fat\":4.5,\"Saturated_fat\":0,\"Sugars\":0.5,\"Salt\":0.5},\"Price\":2.2,\"Prep_time\":7,\"Parallel_time\":5,\"Batch_time\":7,\"Ingredients\":[\"POTATOES\",\"SUNFLOWER OIL\",\"RICE FLOUR\",\"POTATO STARCH\",\"SALT\",\"BINDING AGENT\",\"PARIKA\"],\"Alergens\":[\"PAPRIKA\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Curley fries\",\"Subtitle\":\"Crispy, curly and fun\",\"Desc\":\"Curled pottato fries\",\"P1\":\"Our classic crispy and fluffy seasoned fries with a fun twist\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":135,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":0.7,\"Cholesterol\":1.1,\"Sodium\":0.4,\"Total_carbohydrates\":23,\"Dietary_fibre\":3,\"Added_sugar\":0.1,\"Sugar_alcohol\":0,\"Protein\":2.5,\"Calcium\":0.2,\"Iron\":0.1,\"Vitamin_d\":0,\"Potassium\":0.2,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.2,\"Vitamin_B12\":0.3}'),
(2004, 'Tomato dip', '\\2000-Sides\\2004-Tomato_dip\\C:\\httpd-2.4.53-w', 0.75, 0, 0, '{\"Nutritional_info\":{\"Calories\":19.8,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":0.21,\"Salt\":0.03},\"Price\":0.75,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"TOMATOES\",\"VINEGAR\",\"LEMON JUICE\",\"POTASSIUM CHLORIDE\",\"CITRUS FIBRE\",\"HERB EXTRACTS\",\"SUCRALOSE\"],\"Alergens\":[\"CELERY\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Tomato dip\",\"Subtitle\":\"A classic dipping sauce\",\"Desc\":\"Tomato ketchup dip\",\"P1\":\"Smooth, creamy and rich tommato ketchup sauce dip\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":50,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0.3,\"Total_carbohydrates\":2.4,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.6,\"Calcium\":0.1,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":1.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(2005, 'BBQ dip', '\\2000-Sides\\2005-BBQ_dip\\C:\\httpd-2.4.53-win6', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":64,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":12.1,\"Salt\":0.7},\"Price\":0.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"TOMATOES\",\"SYRUP\",\"VINEGAR\",\"SUGAR\",\"MOLASSES\",\"HONEY\",\"CORNFLOUR\",\"SALT\",\"SMOKE FLAVOURINGS\",\"SPICES\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"BBQ dip\",\"Subtitle\":\"Sweet and tangy\",\"Desc\":\"Honey BBQ sauce\",\"P1\":\"Honey Woodsmoke BBQ Sauce\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":50,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":15.3,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.25,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.3}'),
(2006, 'Mayo dip', '\\2000-Sides\\2006-Mayo_dip\\C:\\httpd-2.4.53-win', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":322,\"Total_fat\":35,\"Saturated_fat\":0,\"Sugars\":1.5,\"Salt\":0.5},\"Price\":0.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"RAPESEED OIL\",\"WATER\",\"EGG YOLK\",\"VINEGAR\",\"SUGAR\",\"STARCH\",\"SALT\",\"MUSTARD\",\"SPICES\"],\"Alergens\":[\"MUSTARD\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Mayo dip\",\"Subtitle\":\"Simple and tasty\",\"Desc\":\"Vegetarian mayonnaise dip\",\"P1\":\"Vegetarian mayo dip, made with free range eggs.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"Gluten and lactose free\",\"Minor_note\":\"\"}', '{\"Serving_size\":50,\"Trans_fat\":3.2,\"Polyunsaturated_fat\":3.2,\"Monounsaturated_fat\":5.3,\"Cholesterol\":0.3,\"Sodium\":0.2,\"Total_carbohydrates\":3,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.1,\"Calcium\":0.5,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(2007, 'Onion rings', '\\2000-Sides\\2007-Onion_rings\\C:\\httpd-2.4.53-', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":285,\"Total_fat\":16,\"Saturated_fat\":0,\"Sugars\":3.1,\"Salt\":0.9},\"Price\":1.99,\"Prep_time\":6,\"Parallel_time\":5,\"Batch_time\":6,\"Ingredients\":[\"ONIONS\",\"FLOUR\",\"RAPESEED OIL\",\"MAIZE\",\"SALT\",\"DEXTROSE\",\"STARCH\",\"PEPPER\",\"TUMERIC\"],\"Alergens\":[\"TUMERIC\",\"EGGS\"],\"Warnings\":[\"CONTAINS WHEAT\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Onion rings\",\"Subtitle\":\"Classic crispy treat\",\"Desc\":\"Batter fried onion rings\",\"P1\":\"Delicious, well seasoned onion rings in a rich, crispy batter fried coating\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0.5,\"Polyunsaturated_fat\":0.5,\"Monounsaturated_fat\":4.6,\"Cholesterol\":0.8,\"Sodium\":0.1,\"Total_carbohydrates\":29,\"Dietary_fibre\":3.8,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":4,\"Calcium\":0,\"Iron\":0.8,\"Vitamin_d\":0.1,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0.1}'),
(2008, 'Baked beans', '\\2000-Sides\\2008-Baked_beans\\C:\\httpd-2.4.53-', 1.25, 0, 0, '{\"Nutritional_info\":{\"Calories\":156,\"Total_fat\":0.4,\"Saturated_fat\":0,\"Sugars\":9.4,\"Salt\":1.2},\"Price\":1.25,\"Prep_time\":4,\"Parallel_time\":3,\"Batch_time\":4,\"Ingredients\":[\"BEANS\",\"TOMATOES\",\"WATER\",\"SUGAR\",\"VINEGAR\",\"CORNFLOUR\",\"SALT\",\"SPICE\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Baked beans\",\"Subtitle\":\"A classic british side\",\"Desc\":\"Baked beans in tomato sauce\",\"P1\":\"Tasty baked beans in a rich and creamy tomato sauce\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":200,\"Trans_fat\":0.025,\"Polyunsaturated_fat\":0.025,\"Monounsaturated_fat\":0.1,\"Cholesterol\":0.5,\"Sodium\":0.1,\"Total_carbohydrates\":25,\"Dietary_fibre\":7.4,\"Added_sugar\":1,\"Sugar_alcohol\":0,\"Protein\":9.4,\"Calcium\":0.6,\"Iron\":0.3,\"Vitamin_d\":1,\"Potassium\":0.2,\"Vitamin_a\":1,\"Vitamin_c\":1,\"Vitamin_e\":1,\"Vitamin_B12\":2}'),
(2009, 'Hash browns', '\\2000-Sides\\2009-Hash_browns\\C:\\httpd-2.4.53-', 1.25, 0, 0, '{\"Nutritional_info\":{\"Calories\":288,\"Total_fat\":13.2,\"Saturated_fat\":0,\"Sugars\":1.2,\"Salt\":0.7},\"Price\":1.25,\"Prep_time\":9,\"Parallel_time\":5,\"Batch_time\":9,\"Ingredients\":[\"POTATO\",\"SUNFLOWER OIL\",\"ONION\",\"SALT\",\"DEXTROS\",\"ONION POWDER\",\"WHITE PEPPER\"],\"Alergens\":[\"ONION\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Hash browns\",\"Subtitle\":\"A tasty, crispy snack\",\"Desc\":\"Seasoned hash browns\",\"P1\":\"Delicious hash browns make with potatoes and sunflower oil, seasoned with onion, salt and pepper\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":162,\"Trans_fat\":0.9,\"Polyunsaturated_fat\":0.9,\"Monounsaturated_fat\":3.2,\"Cholesterol\":1.5,\"Sodium\":0.75,\"Total_carbohydrates\":36.9,\"Dietary_fibre\":3.6,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":3.5,\"Calcium\":2,\"Iron\":0.2,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(2010, 'Coleslaw', '\\2000-Sides\\2010-Coleslaw\\C:\\httpd-2.4.53-win', 1.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":150,\"Total_fat\":13.8,\"Saturated_fat\":0,\"Sugars\":3.7,\"Salt\":0.6},\"Price\":1,\"Prep_time\":3,\"Parallel_time\":0,\"Batch_time\":3,\"Ingredients\":[\"CABBAGE\",\"CARROT\",\"RAPESEED OIL\",\"WATER\",\"CREAM\",\"SUGAR\",\"EGG\",\"LEMON JUICE\",\"VINEGAR\",\"ONION\",\"SALT\",\"CHIVE\",\"POTATO STARCH\",\"CITRUS FIBRE\"],\"Alergens\":[\"EGG\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Coleslaw\",\"Subtitle\":\"A seriously tasty vegan side\",\"Desc\":\"Cabage, carrot and mayo coleslaw\",\"P1\":\"A Cabage, carrot, cream and mayo coleslaw flavoured with lemon juice, vinegar, onion, salt and pepper\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":50,\"Trans_fat\":0.23,\"Polyunsaturated_fat\":0.23,\"Monounsaturated_fat\":8.2,\"Cholesterol\":2,\"Sodium\":0.4,\"Total_carbohydrates\":5.1,\"Dietary_fibre\":1,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.7,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(2011, 'Cucumber slices', '\\2000-Sides\\2011-Cucumber_slices\\C:\\httpd-2.4', 0.75, 0, 0, '{\"Nutritional_info\":{\"Calories\":11,\"Total_fat\":0.5,\"Saturated_fat\":0,\"Sugars\":0.9,\"Salt\":0.01},\"Price\":0.75,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":1,\"Ingredients\":[\"CUCUMBER\",\"VINEGAR\",\"SALT\",\"PEPPER\",\"OIL\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:SIDES\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Cucumber slices\",\"Subtitle\":\"A light and healthy snack\",\"Desc\":\"Sliced cucumber\",\"P1\":\"1 whole sliced cucumber, neatly stacked and seasoned with vinegar, salt and pepper\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":0.9,\"Dietary_fibre\":0.6,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.8,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3000, 'Plain cheescake', '\\3000-Desserts\\3000-Plain_cheesecake\\C:\\httpd', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":488,\"Total_fat\":32.3,\"Saturated_fat\":0,\"Sugars\":23.2,\"Salt\":0.4},\"Price\":1.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":25,\"Ingredients\":[\"SOFT CHEESE\",\"MILK\",\"CREAM\",\"FLOUR\",\"EGG\",\"SUGAR\",\"SOUR CREAM\",\"PALM FAT\",\"BROWN SUGAR\",\"FLAVOURING\",\"SUGAR SYRUP\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS EGG\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Plain cheescake\",\"Subtitle\":\"Classic and classy\",\"Desc\":\"New york vanila cheesecake\",\"P1\":\"A baked vanilla cheesecake with a crispy and crumbly biscuit base, in a classic new york style.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"Consists of a slice of 1 third of a cake\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0.7,\"Polyunsaturated_fat\":0.7,\"Monounsaturated_fat\":3.8,\"Cholesterol\":0.8,\"Sodium\":0.7,\"Total_carbohydrates\":39.8,\"Dietary_fibre\":1,\"Added_sugar\":3,\"Sugar_alcohol\":0,\"Protein\":8.2,\"Calcium\":3.8,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(3001, 'Raspberry cheesecake', '\\3000-Desserts\\3001-Raspberry_cheesecake\\C:\\h', 2.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":548,\"Total_fat\":32,\"Saturated_fat\":0,\"Sugars\":32,\"Salt\":0.32},\"Price\":2.5,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":27,\"Ingredients\":[\"SOFT CHEESE\",\"MILK\",\"SUAGR\",\"CREAM\",\"WHEAT FLOUR\",\"RASPBERRY PUREE\",\"EGG\",\"RASPBERRIES\",\"OATMEAL\",\"RAPESEED OIL\",\"WATER\",\"WHEY POWDER\"],\"Alergens\":[\"RASPBERRY\"],\"Warnings\":[\"CONTAINS EGGS\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Raspberry cheesecake\",\"Subtitle\":\"A tasty fruit cheesecake\",\"Desc\":\"Raspberry flavour cheesecake\",\"P1\":\"A delicious creamy cheesecake with sweet raspberry puree sauce wound in.\",\"P2\":\"Served atop a crumbly biscuit base and topped with raspberries\",\"P3\":\"\",\"Major_note\":\"Consists of a slice of 1 third of a cake\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":4.8,\"Cholesterol\":6.1,\"Sodium\":0.1,\"Total_carbohydrates\":58,\"Dietary_fibre\":1.8,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":7.4,\"Calcium\":5.5,\"Iron\":0.2,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(3002, 'Chocolate cheesecake', '\\3000-Desserts\\3002-Chocolate_cheesecake\\C:\\h', 2.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":428,\"Total_fat\":21.4,\"Saturated_fat\":0,\"Sugars\":29.4,\"Salt\":0.34},\"Price\":2.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":28,\"Ingredients\":[\"CREAM\",\"MILK\",\"WHEAT\",\"SOFT CHEESE\",\"SUGAR\",\"PALM FAT\",\"EGG\",\"BROWN SUGAR\",\"COCOA POWDER\",\"MILK CHOCOLATE\",\"CHOCOLATE CURLS\",\"COCOA BUTTER\",\"BUTTER\",\"COCOA POWDER\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS EGGS\",\"MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chocolate cheesecake\",\"Subtitle\":\"A rich and Luxurious cheesecake\",\"Desc\":\"A Chocolate cheescake with a chocolate base\",\"P1\":\"Cheesecake mixed cocoa powder and butter, finished with chocolate curls and sauce.\",\"P2\":\"Served on a base of crumbly chocolate biscuits\",\"P3\":\"\",\"Major_note\":\"Consists of a slice of 1 third of a cake\",\"Minor_note\":\"\"}', '{\"Serving_size\":140,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":4.1,\"Cholesterol\":3.2,\"Sodium\":0.1,\"Total_carbohydrates\":48.8,\"Dietary_fibre\":2.4,\"Added_sugar\":5.8,\"Sugar_alcohol\":0,\"Protein\":9,\"Calcium\":5.6,\"Iron\":0.2,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}');
INSERT INTO `Products` (`ID`, `Name`, `Info`, `Price`, `Stock`, `Promoted`, `Desc_json`, `Info_json`, `Add_info_json`) VALUES
(3003, 'Millionares cheesecake', '\\3000-Desserts\\3003-Millionares_cheesecake\\C:', 1.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":584,\"Total_fat\":34,\"Saturated_fat\":0,\"Sugars\":24,\"Salt\":0.8},\"Price\":1,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":28,\"Ingredients\":[\"CREAM\",\"MILK\",\"SOFT CHEESE\",\"BISCUIT CRUMB\",\"WHET\",\"SUNFLOWER OIL\",\"SUGAR\",\"GLUCOSE SYRUP\",\"SEA SALT\",\"GLUCOSE POWDER\",\"DARK CHOCOLATE\",\"COCOA BUTTTER\",\"VANILA POWDER\",\"WATER\",\"CARAMEL SYRUP\",\"BUTTER\",\"COCONUT OIL\",\"EGG YOLK\",\"VANILLA SEEDS\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK AND EGGS\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Millionares cheesecake\",\"Subtitle\":\"A classic Luxury\",\"Desc\":\"Traditional millionares cheesecake\",\"P1\":\"A luxurious cheesecake topped with rich chocolate and featuring an indulgent caramel sauce.\",\"P2\":\"Served on a golden buscuit base.\",\"P3\":\"\",\"Major_note\":\"Consists of a slice of 1 third of a cake\",\"Minor_note\":\"\"}', '{\"Serving_size\":170,\"Trans_fat\":0.4,\"Polyunsaturated_fat\":0.4,\"Monounsaturated_fat\":4.3,\"Cholesterol\":5.9,\"Sodium\":0.3,\"Total_carbohydrates\":58,\"Dietary_fibre\":2.8,\"Added_sugar\":5,\"Sugar_alcohol\":0,\"Protein\":8.6,\"Calcium\":3.5,\"Iron\":0.2,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(3004, 'Brownies', '\\3000-Desserts\\3004-Brownies\\C:\\httpd-2.4.53-', 1.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":466,\"Total_fat\":25.6,\"Saturated_fat\":0,\"Sugars\":40,\"Salt\":0.3},\"Price\":1.5,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":20,\"Ingredients\":[\"SUGAR\",\"MILK CHOCOLATE\",\"COCOA BUTTER\",\"VEGETABLE OIL\",\"WHEAT FLOUR\",\"WATER\",\"GLUCOSE SYRUP\",\"COCOA POWDER\",\"EGG\",\"SALT\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS EGG AND MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Brownies\",\"Subtitle\":\"Tasty chocolate bites\",\"Desc\":\"Chocolate mini brownies\",\"P1\":\"A serving tasty sugary chocolate mini treats with a chocolate topping.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0.2,\"Polyunsaturated_fat\":0.2,\"Monounsaturated_fat\":5.9,\"Cholesterol\":0.8,\"Sodium\":0.2,\"Total_carbohydrates\":53.3,\"Dietary_fibre\":2.5,\"Added_sugar\":23,\"Sugar_alcohol\":0,\"Protein\":4.7,\"Calcium\":1.3,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(3005, 'Vanilla ice cream', '\\3000-Desserts\\3005-Vanilla_ice_cream\\C:\\http', 0.75, 0, 0, '{\"Nutritional_info\":{\"Calories\":92,\"Total_fat\":4.4,\"Saturated_fat\":0,\"Sugars\":7.5,\"Salt\":0.06},\"Price\":0.75,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":1,\"Ingredients\":[\"MILK\",\"GLUCOSE SYRUP\",\"WATER\",\"COCONUT OIL\",\"WHEY POWDER\",\"VANILLA PODS\"],\"Alergens\":[\"VANILLA\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Vanilla ice cream\",\"Subtitle\":\"Smooth and cooling\",\"Desc\":\"Traditional vanilla ice cream\",\"P1\":\"A classic smooth and creamy vanila ice cream.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.4,\"Cholesterol\":0.1,\"Sodium\":0,\"Total_carbohydrates\":12,\"Dietary_fibre\":0.5,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":0.9,\"Calcium\":5,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3006, 'Bannana ice cream', '\\3000-Desserts\\3006-Bannana_ice_cream\\C:\\http', 0.75, 0, 0, '{\"Nutritional_info\":{\"Calories\":92,\"Total_fat\":4.4,\"Saturated_fat\":0,\"Sugars\":7.5,\"Salt\":0.06},\"Price\":0.75,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":1,\"Ingredients\":[\"MILK\",\"GLUCOSE SYRUP\",\"WATER\",\"COCONUT OIL\",\"WHEY POWDER\",\"BANNANA\",\"BANNANA EXTRACT\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Bannana ice cream\",\"Subtitle\":\"A tasty summer treat\",\"Desc\":\"Ice cream with bannana and flavourings\",\"P1\":\"Smooth and creamy ice cream with bannana flavourings, topped with sliced bannanas\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.4,\"Cholesterol\":0.1,\"Sodium\":0,\"Total_carbohydrates\":12,\"Dietary_fibre\":0.05,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":0.09,\"Calcium\":5,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3007, 'Chocolate ice cream', '\\3000-Desserts\\3007-Chocolate_ice_cream\\C:\\ht', 1.25, 0, 0, '{\"Nutritional_info\":{\"Calories\":196,\"Total_fat\":8.7,\"Saturated_fat\":0,\"Sugars\":20,\"Salt\":0.11},\"Price\":1.25,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":1,\"Ingredients\":[\"MILK\",\"GLUCOSE SYRUP\",\"WATER\",\"COCONUT OIL\",\"WHEY POWDER\",\"COCOA POWDER\",\"MILK CHOCOLATE\",\"COCOA BUTTER\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chocolate ice cream\",\"Subtitle\":\"Rich and decidant\",\"Desc\":\"Rich chocolate ice cream\",\"P1\":\"Rich, creamy and indulgent chocolate ice cream made with organic cocoa powder and butter.\",\"P2\":\"Seasoned with a small hint of coconut oil.\",\"P3\":\"blended with milk chocolate slithers for extra chocolaty goodness\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":24,\"Dietary_fibre\":0,\"Added_sugar\":3,\"Sugar_alcohol\":0,\"Protein\":4,\"Calcium\":4,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3008, 'Neapolitan ice cream', '\\3000-Desserts\\3008-Neapolitan_ice_cream\\C:\\h', 1.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":94,\"Total_fat\":4.5,\"Saturated_fat\":0,\"Sugars\":9.3,\"Salt\":0},\"Price\":1,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":1,\"Ingredients\":[\"MILK\",\"GLUCOSE SYRUP\",\"SUGAR\",\"COCONUT OIL\",\"WHEY POWDER\",\"COCOA POWDER\",\"MILK CHOCOLATE\",\"BUTTER\",\"SOYA LECITHINS\",\"BANANNA EXTRACT\",\"BANNANA\"],\"Alergens\":[\"VANILLA\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Neapolitan ice cream\",\"Subtitle\":\"A classic mix\",\"Desc\":\"Banna,chocolate and vanilla ice cream\",\"P1\":\"Cant decide what ice cream you want? try this classic combination for a little bit of everything.\",\"P2\":\"Featuring smooth vanila, Delicious bannana and rich chocolate\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":125,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.3,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":14.1,\"Dietary_fibre\":0.3,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":1.2,\"Calcium\":6,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3009, 'Ice cream sundae', '\\3000-Desserts\\3009-Ice_cream_sundae\\C:\\httpd', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":249,\"Total_fat\":13,\"Saturated_fat\":0,\"Sugars\":23,\"Salt\":0.28},\"Price\":1.99,\"Prep_time\":4,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"SUGAR\",\"CREAM\",\"MILK\",\"WATER\",\"GLUCOSE SYRUP\",\"COCONUT FAT\",\"VEGE OILS\",\"BANANA PUREE\",\"STARCH\",\"EGG YOLK\",\"WHEAT FLOUR\",\"BUTTER\",\"CORN FIBRE\",\"COCOA POWDER\",\"MILK POWDER\",\"COCOA POWDER\",\"SLAT\",\"MOLASSES\",\"VANILLA\",\"BUTTER\",\"BANNANA\"],\"Alergens\":[\"VANILLA\"],\"Warnings\":[\"CONTAINS MILK\",\"MAY CONTAIN NUTS\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Ice cream sundae\",\"Subtitle\":\"Deliciously sweet and creamy\",\"Desc\":\"Banoffee flavour sundae\",\"P1\":\"An increadable sundae featuring banana ice cream with chocolate \\u0026 caramel cups.\",\"P2\":\"Includes whipped cream,Caramel swirls,Cookie chunks,Chocolate chunks.\",\"P3\":\"Drizzeled with chocolate and bannana sauce\",\"Major_note\":\"May contain nuts\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.8,\"Cholesterol\":0.1,\"Sodium\":0.1,\"Total_carbohydrates\":29,\"Dietary_fibre\":0,\"Added_sugar\":5,\"Sugar_alcohol\":0,\"Protein\":2.7,\"Calcium\":12,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3010, 'Ice cream cake', '\\3000-Desserts\\3010-Ice_cream_cake\\C:\\httpd-2', 2.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":244,\"Total_fat\":14,\"Saturated_fat\":0,\"Sugars\":20,\"Salt\":0.08},\"Price\":2.5,\"Prep_time\":3,\"Parallel_time\":0,\"Batch_time\":10,\"Ingredients\":[\"SKIMMED MILK\",\"COCONUT FAT\",\"GLUCOSE SYRUP\",\"SUGAR\",\"WATER\",\"COCOA POWDER\",\"WHEY SOLIDS\",\"STARCH\",\"BEETROOT JUICE\",\"CORN STARCH\",\"VANILLA\",\"SUGAR SYRUP\",\"BLACKCURRANT CONCENTRATE\",\"LEMON CONCENTRATE\"],\"Alergens\":[\"VANILLA\",\"LEMON\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Ice cream cake\",\"Subtitle\":\"A delicous treat\",\"Desc\":\"Cake made of chocolate and icecream\",\"P1\":\"Delicious vanila and bannana ice cream betwtween chocolate\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":175,\"Trans_fat\":0.5,\"Polyunsaturated_fat\":0.5,\"Monounsaturated_fat\":3.2,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":27,\"Dietary_fibre\":0,\"Added_sugar\":5,\"Sugar_alcohol\":0,\"Protein\":2.1,\"Calcium\":8,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3011, 'Chocolate cake', '\\3000-Desserts\\3011-Chocolate_cake\\C:\\httpd-2', 1.75, 0, 0, '{\"Nutritional_info\":{\"Calories\":416,\"Total_fat\":22,\"Saturated_fat\":0,\"Sugars\":27,\"Salt\":0.4},\"Price\":1.75,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":35,\"Ingredients\":[\"SUGAR\",\"WHEAT\",\"FLOUR\",\"CALCUIM CARBONATE\",\"RAPESEED OIL\",\"EGG\",\"UNSALTED BUTTER\",\"GLUCOSE SYRUP\",\"COCOA POWDER\",\"MILK CHOCOLATE\",\"WHITE CHOCOLATE\",\"MILK\",\"CORNFLOUR\",\"WHIPPED CREAM\",\"SUGAR SYRUP\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chocolate cake\",\"Subtitle\":\"Rich and tasty\",\"Desc\":\"Tripple chocolate cake\",\"P1\":\"A decedant chocolate cake, with chocolate cream and white and milk chocolate flakes\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":0.8,\"Polyunsaturated_fat\":0.8,\"Monounsaturated_fat\":4.3,\"Cholesterol\":0.8,\"Sodium\":0.1,\"Total_carbohydrates\":49,\"Dietary_fibre\":0.3,\"Added_sugar\":5,\"Sugar_alcohol\":0,\"Protein\":4.4,\"Calcium\":1.5,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3012, 'Red velvet cake', '\\3000-Desserts\\3012-Red_velvet_cake\\C:\\httpd-', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":364,\"Total_fat\":27,\"Saturated_fat\":0,\"Sugars\":9,\"Salt\":0.18},\"Price\":1.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":37,\"Ingredients\":[\"WHIPPED CREAM\",\"RED BISCUIT\",\"WHEAT\",\"FLOUR\",\"SUGAR\",\"VEGETABLE OIL\",\"SUGAR SYRUP\",\"CANE SUGAR\",\"WHEY POWDER\",\"MILK\",\"EGGS\",\"SOFT CHEESE.COCOA BUTTER\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTIAINS MILK AND EGGS\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Red velvet cake\",\"Subtitle\":\"A stand out dish\",\"Desc\":\"Vanilla velvet cheesecake\",\"P1\":\"A delicious re-imagining of the eye catching red velevt cake\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":164,\"Trans_fat\":0.9,\"Polyunsaturated_fat\":0.9,\"Monounsaturated_fat\":3.7,\"Cholesterol\":0.43,\"Sodium\":0,\"Total_carbohydrates\":27,\"Dietary_fibre\":0.5,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":3.1,\"Calcium\":1.5,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3013, 'Victoria sponge cake', '\\3000-Desserts\\3013-Victoria_sponge_cake\\C:\\h', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":431,\"Total_fat\":18.9,\"Saturated_fat\":0,\"Sugars\":44.1,\"Salt\":0.48},\"Price\":1.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":43,\"Ingredients\":[\"SUGAR\",\"POTATO STARCH\",\"ICING SUGAR\",\"PLAM OIL\",\"COCOUNUT OIL\",\"FLAVOURING\",\"EGG\",\"STRAWBERRY JAM\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK AND EGGS\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Victoria sponge cake\",\"Subtitle\":\"An english tradition\",\"Desc\":\"Strawberry jam sponge cake\",\"P1\":\"4 slices of a tradtional smooth and silky victoria sponge cake.\",\"P2\":\"Held together with sweeted whipped cream and strawberry jam\",\"P3\":\"\",\"Major_note\":\"4 slices\",\"Minor_note\":\"\"}', '{\"Serving_size\":100,\"Trans_fat\":1.1,\"Polyunsaturated_fat\":1.1,\"Monounsaturated_fat\":8.6,\"Cholesterol\":3.5,\"Sodium\":0.5,\"Total_carbohydrates\":62.4,\"Dietary_fibre\":1.1,\"Added_sugar\":10,\"Sugar_alcohol\":0,\"Protein\":2.3,\"Calcium\":2.3,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3014, 'Jam doughnuts', '\\3000-Desserts\\3014-Jam_doughnuts\\C:\\httpd-2.', 1.00, 0, 0, '{\"Nutritional_info\":{\"Calories\":400,\"Total_fat\":19.4,\"Saturated_fat\":0,\"Sugars\":13,\"Salt\":0.84},\"Price\":1,\"Prep_time\":2,\"Parallel_time\":0,\"Batch_time\":15,\"Ingredients\":[\"FLOUR\",\"CREAM\",\"JAM\",\"SUGAR\",\"PLUM PUREE\",\"APPLE PUREE\",\"BLACKCURRANT PUREE\",\"WATER\",\"PLAM OIL\",\"YEAST\",\"SALT\",\"FLOUR\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS EGGS AND MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Jam doughnuts\",\"Subtitle\":\"Classic jamy goodness\",\"Desc\":\"Strawberry jam filled dougnuts\",\"P1\":\"A pair of simple sugared doughnuts stuffed with strawberry jam\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"2 doughnuts per serving\",\"Minor_note\":\"\"}', '{\"Serving_size\":116,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":3.4,\"Cholesterol\":1.2,\"Sodium\":0,\"Total_carbohydrates\":48,\"Dietary_fibre\":3.8,\"Added_sugar\":4,\"Sugar_alcohol\":0,\"Protein\":11.6,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3015, 'Chocolate doughnuts', '\\3000-Desserts\\3015-Chocolate_doughnuts\\C:\\ht', 1.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":337,\"Total_fat\":19.1,\"Saturated_fat\":0,\"Sugars\":17.8,\"Salt\":0.21},\"Price\":1.5,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":18,\"Ingredients\":[\"WHEAT FLOUR\",\"VEGETABLE OIL\",\"COCOUNT\",\"SUGAR\",\"WATER\",\"MILK CHOCOLATE\",\"SUAGAR\",\"COCOA BUTTER\",\"WHEY POWDER\",\"MILK\",\"YEAST\",\"MILK POWDER\",\"SOY FLOUR\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chocolate doughnuts\",\"Subtitle\":\"A chocolaty treat\",\"Desc\":\"Chocolate covered dougnut with sprinkles\",\"P1\":\"Classic glazed ring doughnuts with a chocolate topping, with chocolate sprinkles\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":74,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":4.2,\"Cholesterol\":0.7,\"Sodium\":0.1,\"Total_carbohydrates\":35.4,\"Dietary_fibre\":1.2,\"Added_sugar\":5,\"Sugar_alcohol\":0,\"Protein\":4.2,\"Calcium\":1.1,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(3016, 'Sprinkle ring doughnuts', '\\3000-Desserts\\3016-Sprinkle_ring_doughnuts\\C', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":213,\"Total_fat\":9.2,\"Saturated_fat\":0,\"Sugars\":8.6,\"Salt\":0.18},\"Price\":0.99,\"Prep_time\":2,\"Parallel_time\":0,\"Batch_time\":14,\"Ingredients\":[\"FORTIFIED WHEAT FLOUR\",\"WATER\",\"PINK ICING\",\"SUGAR\",\"COCONUT OIL\",\"MILK POWDER\",\"PALM OIL\",\"SUGAR\",\"YEAST\",\"CORN STARCH\",\"MAIZE STARCH\",\"POTATO STARCH\",\"SALT\",\"SOYA FLOWER\"],\"Alergens\":[\"\"],\"Warnings\":[\"CONTAINS MILK\"],\"Tags\":[\"CATEGORY:DESSERTS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Sprinkle ring doughnuts\",\"Subtitle\":\"Classic sprinkle doughnuts\",\"Desc\":\"Strawberry doughnut with sprinkles\",\"P1\":\"The classic american style glazed doughnut with a strawberry coating and mixed sprinkles.\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":75,\"Trans_fat\":0.3,\"Polyunsaturated_fat\":0.3,\"Monounsaturated_fat\":2.9,\"Cholesterol\":0.5,\"Sodium\":0.1,\"Total_carbohydrates\":28.6,\"Dietary_fibre\":1.7,\"Added_sugar\":2,\"Sugar_alcohol\":0,\"Protein\":3.2,\"Calcium\":1.1,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4000, 'Classic cola', '\\4000-Drinks\\4000-Cola\\C:\\httpd-2.4.53-win64-', 1.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":10,\"Total_fat\":5,\"Saturated_fat\":0,\"Sugars\":53,\"Salt\":1},\"Price\":1.5,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"SYRUP\",\"WATER\",\"SUGAR\",\"SYNTHETIC VANILA EXTRACT\",\"ACETIC ACID\",\"CAFFINE\",\"ARTIFICIAL FLAVORINGS\"],\"Alergens\":[\"CAFFINE\"],\"Warnings\":[\"CARBONATED\",\"HIGH IN SUGAR\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Classic cola\",\"Subtitle\":\"Fizzy and tasty\",\"Desc\":\"The classic carbonated fiz you love\",\"P1\":\"For over 50 years classic cola has been quenching your thirst in style, refreshing, exciting and with an unmistakable taste, you know it, you love it.\",\"P2\":\"An instantly recognisable and widely enjoyed pick-me-up classic cola is a brilliant choice for when you want something you know you\\u0027l love.\",\"P3\":\"Sold in over 130 countries, a can of classic cola is a worldwide favourite.\",\"Major_note\":\"High in sugar, contains caffine\",\"Minor_note\":\"Recyclable can\"}', '{\"Serving_size\":301,\"Trans_fat\":0.1,\"Polyunsaturated_fat\":0.1,\"Monounsaturated_fat\":0.2,\"Cholesterol\":0.3,\"Sodium\":0.9,\"Total_carbohydrates\":0.5,\"Dietary_fibre\":1.2,\"Added_sugar\":45,\"Sugar_alcohol\":0,\"Protein\":0.5,\"Calcium\":0.1,\"Iron\":0.1,\"Vitamin_d\":0,\"Potassium\":0.01,\"Vitamin_a\":0,\"Vitamin_c\":0.03,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4001, 'Tea', '\\4000-Drinks\\4001-Tea\\C:\\httpd-2.4.53-win64-V', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":35,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":0.1,\"Salt\":0},\"Price\":1.99,\"Prep_time\":3,\"Parallel_time\":2,\"Batch_time\":0,\"Ingredients\":[\"BLACK TEA\",\"MILK\",\"SUGAR\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Tea\",\"Subtitle\":\"An english classic\",\"Desc\":\"Yorkshire black tea.\",\"P1\":\"Relax with a proper brew, enjoy a fine british tradition with this lovely cup of tea.\",\"P2\":\"Served with your desired ammount of milk and sugar\",\"P3\":\"\",\"Major_note\":\"Variable sugar and milk\",\"Minor_note\":\"\"}', '{\"Serving_size\":31,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":0,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0.1,\"Protein\":0.1,\"Calcium\":0,\"Iron\":0.1,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(4002, 'Coffee', '\\4000-Drinks\\4002-Coffee\\C:\\httpd-2.4.53-win6', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":4,\"Total_fat\":0.5,\"Saturated_fat\":0,\"Sugars\":0.5,\"Salt\":0.02},\"Price\":1.99,\"Prep_time\":3,\"Parallel_time\":2,\"Batch_time\":0,\"Ingredients\":[\"COFFEE\",\"MILK\",\"SUGAR\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Coffee\",\"Subtitle\":\"A delicious burst of energy\",\"Desc\":\"Fully caffinated coffee\",\"P1\":\"Our coffee tastes delicious and has a perfect,bold aroma, so you can enjoy your energy boost\",\"P2\":\"Served with your desired amount of milk and sugar\",\"P3\":\"\",\"Major_note\":\"Optional milk and sugar\",\"Minor_note\":\"\"}', '{\"Serving_size\":29,\"Trans_fat\":0.05,\"Polyunsaturated_fat\":0.05,\"Monounsaturated_fat\":0.2,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":0.5,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.5,\"Calcium\":0.1,\"Iron\":0,\"Vitamin_d\":0.1,\"Potassium\":0.1,\"Vitamin_a\":0.1,\"Vitamin_c\":0.1,\"Vitamin_e\":0.1,\"Vitamin_B12\":0.1}'),
(4003, 'Orange juice', '\\4000-Drinks\\4003-Orange_juice\\C:\\httpd-2.4.5', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":62,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":13,\"Salt\":0},\"Price\":0.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"ORANGE JUICE\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Orange juice\",\"Subtitle\":\"A taste of summer\",\"Desc\":\"Fresh Orange juice\",\"P1\":\"Delicious freshly squeezed orange juice from organic oranges\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":14,\"Dietary_fibre\":1.2,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":1.2,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":285,\"Vitamin_a\":0,\"Vitamin_c\":0.26,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4004, 'Apple juice', '\\4000-Drinks\\4004-Apple_juice\\C:\\httpd-2.4.53', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":68,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":15,\"Salt\":0},\"Price\":0.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"APPLE JUICE\",\"ANTIOXIDANT\",\"ASORBIC ACID\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Apple juice\",\"Subtitle\":\"A tasty drink\",\"Desc\":\"Fresh apple juice\",\"P1\":\"Freshly squeezed apple juice from organic apples\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":17,\"Dietary_fibre\":0.9,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.3,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0.45,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4005, 'Blackcurrent juice', '\\4000-Drinks\\4005-Blackcurrent_juice\\C:\\httpd', 0.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":85,\"Total_fat\":0,\"Saturated_fat\":0,\"Sugars\":15,\"Salt\":0},\"Price\":0.99,\"Prep_time\":1,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"PRESSED APPLE\",\"PRESSED GRAPES\",\"SQUASHED BLACKCURRANTS\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:TRUE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Blackcurrent juice\",\"Subtitle\":\"A old british favourite\",\"Desc\":\"Fresh blackcurrant juice\",\"P1\":\"Fresh blackcurrant juice, made with organic apples, grapes and blackcurrents\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":20,\"Dietary_fibre\":0.8,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":0.6,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0.53,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4006, 'Hot chocolate', '\\4000-Drinks\\4006-Hot_Chocolate\\C:\\httpd-2.4.', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":99,\"Total_fat\":2.2,\"Saturated_fat\":0,\"Sugars\":16,\"Salt\":0.3},\"Price\":1.99,\"Prep_time\":3,\"Parallel_time\":1,\"Batch_time\":0,\"Ingredients\":[\"WHEY MERMEATE\",\"MILK\",\"SUGAR\",\"COCOA POWDER\",\"COCONUT OIL\",\"MILK CHOCOLATE\",\"WHEY POWDER\",\"SEA SALT\"],\"Alergens\":[\"COCONUT OIL\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:DRINKS\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Hot chocolate\",\"Subtitle\":\"Tasty and warming\",\"Desc\":\"Hot milk chocolate\",\"P1\":\"Luxurious, smooth and delicious hot chocolate, made with milk chocolate and cocoa powder\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":150,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.1,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":18,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":1.3,\"Calcium\":0,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0}'),
(4007, 'Bannana milkshake', '\\4000-Drinks\\4007-Bannana_milkshake\\C:\\httpd-', 1.50, 0, 0, '{\"Nutritional_info\":{\"Calories\":120,\"Total_fat\":2.4,\"Saturated_fat\":0,\"Sugars\":19.2,\"Salt\":0.2},\"Price\":1.5,\"Prep_time\":2,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"MILK\",\"SUGAR\",\"BANANA JUICE\",\"GELLAN GUM\",\"NATURAL FLAVOURING\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:UNDEFINED\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Bannana milkshake\",\"Subtitle\":\"A summer treat\",\"Desc\":\"Fresh banna milkshake\",\"P1\":\"A nice tasty and relatively healthy banana milk drink\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":175,\"Trans_fat\":0.05,\"Polyunsaturated_fat\":0.05,\"Monounsaturated_fat\":4,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":19.2,\"Dietary_fibre\":0,\"Added_sugar\":7,\"Sugar_alcohol\":0,\"Protein\":6,\"Calcium\":2.4,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0.2}'),
(4008, 'Chocolate milkshake', '\\4000-Drinks\\4008-Chocolate_milkshake\\C:\\http', 1.99, 0, 0, '{\"Nutritional_info\":{\"Calories\":130,\"Total_fat\":3,\"Saturated_fat\":0,\"Sugars\":17.8,\"Salt\":0.2},\"Price\":1.99,\"Prep_time\":2,\"Parallel_time\":0,\"Batch_time\":0,\"Ingredients\":[\"MILK\",\"SUGAR\",\"MILK CHOCOLATE\",\"COCOA POWDER\",\"CELLULOSE\"],\"Alergens\":[\"\"],\"Warnings\":[\"\"],\"Tags\":[\"CATEGORY:UNDEFINED\",\"VEGAN:FALSE\",\"VEGETARIAN:TRUE\"]}', '{\"Title\":\"Chocolate milkshake\",\"Subtitle\":\"Tasty chocolate milk\",\"Desc\":\"Premium chocolate milkshake\",\"P1\":\"Delicous and rich chocolate milk\",\"P2\":\"\",\"P3\":\"\",\"Major_note\":\"\",\"Minor_note\":\"\"}', '{\"Serving_size\":175,\"Trans_fat\":0,\"Polyunsaturated_fat\":0,\"Monounsaturated_fat\":0.2,\"Cholesterol\":0,\"Sodium\":0,\"Total_carbohydrates\":18.2,\"Dietary_fibre\":0,\"Added_sugar\":0,\"Sugar_alcohol\":0,\"Protein\":6.6,\"Calcium\":2.4,\"Iron\":0,\"Vitamin_d\":0,\"Potassium\":0,\"Vitamin_a\":0,\"Vitamin_c\":0,\"Vitamin_e\":0,\"Vitamin_B12\":0.2}');

-- --------------------------------------------------------

--
-- Table structure for table `Stock`
--

CREATE TABLE `Stock` (
  `ID` int(4) NOT NULL,
  `Unit_count` int(4) NOT NULL,
  `Unit_Price` double(3,2) NOT NULL,
  `In_stock` tinyint(1) NOT NULL,
  `Last_out` datetime NOT NULL,
  `Last_in` datetime NOT NULL,
  `Out/hour` int(3) NOT NULL,
  `Time_to_0` time NOT NULL COMMENT 'Time to no stock',
  `Low_warn_amount` int(2) NOT NULL,
  `Crit_warn_amount` int(2) NOT NULL COMMENT 'Criticaly low',
  `High_warn_amount` int(4) NOT NULL,
  `Alert_on_low` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `Transactions`
--

CREATE TABLE `Transactions` (
  `ID` varchar(10) NOT NULL COMMENT 'Randomly generated',
  `Time` datetime NOT NULL,
  `Amount` double(4,2) NOT NULL,
  `Recipient` varchar(25) NOT NULL,
  `Sender` varchar(25) NOT NULL,
  `Flag` int(4) NOT NULL COMMENT 'Flag ID code',
  `Hold` tinyint(1) NOT NULL,
  `Approved` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `User factors`
--

CREATE TABLE `User factors` (
  `ID` varchar(10) NOT NULL,
  `Method` int(1) NOT NULL,
  `Contact` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Customers`
--
ALTER TABLE `Customers`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Salt` (`Salt`),
  ADD UNIQUE KEY `2FA_ID` (`2FA_ID`);

--
-- Indexes for table `Employees`
--
ALTER TABLE `Employees`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Salt` (`Salt`),
  ADD UNIQUE KEY `2FA_ID` (`2FA_ID`);

--
-- Indexes for table `Offers`
--
ALTER TABLE `Offers`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `Orders`
--
ALTER TABLE `Orders`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `Products`
--
ALTER TABLE `Products`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `Name` (`Name`),
  ADD UNIQUE KEY `Info` (`Info`);

--
-- Indexes for table `Stock`
--
ALTER TABLE `Stock`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `Transactions`
--
ALTER TABLE `Transactions`
  ADD PRIMARY KEY (`ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
